apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: menthena/udagram-api-feed
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          env:
            - name: POSTGRES_HOST
              value: udacitydb.cjvf92dxt6gy.us-east-2.rds.amazonaws.com
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db
            - name: AWS_BUCKET
              value: udacity-ahmet-microservices-bucket
            - name: AWS_REGION
              value: us-east-2
            - name: AWS_PROFILE
              value: default
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt
            - name: URL
              value: http://localhost
