apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100
  selector:
    app: api-gateway
  type: LoadBalancer
