language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - cd udagram-frontend
  - npm install

# Scripts to be run such as tests
before_script:
  - npm run build
  - cd ../

script:
  - docker --version # print the version for logging
  - docker build -t menthena/udagram-api-feed ./udagram-api-feed
  - docker build -t menthena/udagram-api-user ./udagram-api-user
  - docker build -t menthena/udagram-frontend ./udagram-frontend
  - docker build -t menthena/api-gateway ./api-gateway

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push menthena/udagram-api-feed:latest
  - docker push menthena/udagram-api-user:latest
  - docker push menthena/udagram-frontend:latest
  - docker push menthena/api-gateway:latest
